### ISSUE TITLE
一些配装更新建议

### ISSUE THREAD

**Issue by excosy** [ideless/artifact#21]
托马：饰金4，花神4，或者精通2+2，走绽放路线。
班尼特：删除海染少女，增加教官。
行秋：咋还有用追忆的。如果是指两件套，建议区分一下。两件套需要组选而不是单选，比如攻击2同时包括了角斗追忆辰砂余响，精通2同时包括乐团饰金花神。

尝试根据角色主堆属性自动推荐配装，逻辑可以这么设计：
充能需求：刚需充能(充能沙，如果不需要四件套可携带绝缘2) 副词条歪充能 无需充能(主打普攻重击可带追忆4)
属伤需求：决定是否携带属伤杯
暴击需求：决定是否携带暴击头 特别地，一些西风奶妈可以靠副词条歪暴击
主属性：攻防生精的权重，影响副属性权重和属伤杯下位替代

**Comment by ideless** [comment]
感谢建议！
托马等的配装已修改，在配装修改界面点重置配装就会刷新。但因为暂不支持四星套，教官套没有加进班尼特的配装里。
自动推荐配装的功能我暂时不考虑增加，因为我认为自动推荐的配装不一定准确，总会有一些特殊的角色不适用于一般规律，而且[NGA](https://ngabbs.com/read.php?tid=27859119)上一直在持续更新每个角色的推荐配装，我只要保持同步就好了。

**Comment by excosy** [comment]
有bug，所有风4都变成风2了。砂糖竟然出现了攻风暴配装！
顺便排查一下是不是绽放套花神套也变成了精通2，余响追忆变成攻击2等等。
现有的二件套效果唯一的没有组，但还是有必要标注一下是4件套还是2件套，避免以后替换时再出问题。
比如宗室套，班尼特是宗室4，行秋是宗室2，现在都叫宗室。
另外改个名吧，新增的组叫2件套，原来的套装叫4件套。

**Comment by ideless** [comment]
砂糖的配装我是从[这边](https://ngabbs.com/read.php?pid=635742911)抄来的。
确实绽放套花神套等全变成了一个精通2，二件套和四件套目前在算法上没有区别（和散件有区别），或许应该改个名字叫精通套？
