### ISSUE TITLE
服务端瑶瑶和艾尔海森的配装无法加载出来，本地启动可以

### ISSUE THREAD

**Issue by lijian12345** [ideless/artifact#22]
可能需要重新部署一下？
![chrome_7193r0MjkY](https://user-images.githubusercontent.com/26590220/227726582-0b630376-5cff-409f-b91d-6d161f721aa4.png)
![chrome_UcjX8yHT0W](https://user-images.githubusercontent.com/26590220/227726587-b0a71742-ff03-4f87-8ba8-5616a4734287.png)

**Comment by ideless** [comment]
因为改了数据存储方式，得手动重置配置 :P
![image](https://user-images.githubusercontent.com/94856286/227727240-7f38c23c-74d4-4409-b4d8-99d9ba67feae.png)

**Comment by lijian12345** [comment]
666
