### ISSUE TITLE
有没有可能在“按角色适配率（多人）”排序中，首先按照装备该圣遗物的角色排序

### ISSUE THREAD

**Issue by Saniner** [ideless/artifact#24]
大概就是我想先知道圣遗物适不适合当前角色，其次再看圣遗物最适合哪个角色，这样排序可以说明角色的提升空间，从而辅助决策刷本收益？
这样排序与原来排序相比，好处在于：
1. 未装备的圣遗物两种排序方式相同
2. 对于多个角色适配度差别不大的圣遗物（极好或极差），两种排序方式差别不大
3. 对于不同角色适配度差别较大的圣遗物，因为预览界面能显示排名前2的适配度，这样新排序可以快速找出搭配错误的圣遗物，并进一步判断：
    - 单纯的装错
    - 与该圣遗物最适配的角色，是否已经有更好的圣遗物
    - 与当前装备该圣遗物的角色没那么适配，但是该角色没有更好的选择
感谢作者！

**Comment by ideless** [comment]
已添加（如果我没理解错你的意思的话

**Comment by Saniner** [comment]
辛苦作者了！
我的想法是优先考虑“装备该圣遗物的角色”，比如图中是提那里装备，在这个情况下这个圣遗物的适配率能以提那里的适配度“98.2”排序吗，其次才是迪卢克“98.9”，即使迪卢克适配度更高，但是以“装备者”的适配度为主要关键字来排序是我一开始的想法。
![image](https://user-images.githubusercontent.com/57987311/232208024-4e78e154-e4d6-4238-a4ed-81fb07c045d7.png)

**Comment by ideless** [comment]
现在就是你说的这样，如果已装配就按拥有者的适配概率，否则按最大适配概率。~第一个爆伤头也太好了吧~

**Comment by Saniner** [comment]
刚刚又看了一下，现在明白了，感谢作者！
