### ISSUE TITLE
希望增加一个检查同套装同主词条圣遗物的按钮

### ISSUE THREAD

**Issue by qstdnx** [ideless/artifact#35]
大佬你好，我在使用圣遗物强化助手中经常遇到一个问题
筛选出词条垃圾的圣遗物后，我时常要考虑这个圣遗物是不是独苗。比如我想要精精精风套之类，尽管这时候我的风套精通杯子词条很垃圾，但是我只有这么一个精通杯，所以目前还不能解锁，但是也不想去拉，想等更好的出现再解锁。所以我在解锁许多精通，双爆圣遗物前时常需要先上游戏看看这个主词条的圣遗物是不是独苗。
助手里有一个按上位替代排序的功能，有时候能显示同套装同词条的圣遗物，但是这个功能只能在这个排序下使用，而且很多时候，同套装同词条的圣遗物不会被显示
比如
![image](https://github.com/ideless/artifact/assets/20844622/6ff0d3e7-bee6-4835-9ccc-d99826359034)
如雷精通头我在游戏里一共有三个，但是9个上位替代里没有显示。
![image](https://github.com/ideless/artifact/assets/20844622/23b325f8-c591-4c93-a859-5485c7cf9496)
如果是上位替代的话，更多的应该先参考同套装，同主词条（花和羽毛除外），然后才是小词条相似的

希望大佬能改进一下上位替代的算法，并且能在其他排序里面也能点击显示上位替代圣遗物。

**Comment by ideless** [comment]
上位替代是指主词条和位置一样，**副词条严格更优**的的圣遗物，有的不显示是正常的

我加了一个按钮（比如显示2/10表示有2个风套精通头，10个精通头）：
![](https://github.com/ideless/artifact/assets/94856286/2e56fc9a-e993-4d36-aac9-230b1513aa83)

点开之后弹出对话框（展示对应的精通头，以及根据选中的圣遗物做快速筛选）：
![](https://github.com/ideless/artifact/assets/94856286/a790af58-b79c-4dd3-9e01-0b0889c50494)

**Comment by qstdnx** [comment]
> 上位替代是指主词条和位置一样，**副词条严格更优**的的圣遗物，有的不显示是正常的
> 
> 我加了一个按钮（比如显示2/10表示有2个风套精通头，10个精通头）： ![](https://user-images.githubusercontent.com/94856286/248032884-2e56fc9a-e993-4d36-aac9-230b1513aa83.png)
> 
> 点开之后弹出对话框（展示对应的精通头，以及根据选中的圣遗物做快速筛选）： ![](https://user-images.githubusercontent.com/94856286/248033271-a790af58-b79c-4dd3-9e01-0b0889c50494.png)

感谢更新，问题已完美解决
