### ISSUE TITLE
加锁有bug

### ISSUE THREAD

**Issue by ZhouZiHao-Moon** [ideless/artifact#4]
位置错了，表现出来就是，没有要上锁的上了锁，需要上锁的没上锁，麻烦看看能不能修

**Comment by ideless** [comment]
在用yas-lock导出圣遗物之后到执行加解锁之前有没有进行过强化/删除等操作？yas-lock是按照圣遗物在背包内的位置进行加解锁的，一旦错位就可能出错

**Comment by Kumacytus** [comment]
我也发现了这个问题

在1600x900及1920x1080分辨率下均出现是否加锁识别错误
表现为部分未加锁的识别为加锁，部分加锁的识别为不加锁
（导致后续使用yas-lock进行加解锁完全错乱…
（期间背包里圣遗物无改动

另外，在全部未加锁下进行识别的话
会有一半圣遗物被识别为加锁

**Comment by ideless** [comment]
1. 使用最新版yas-lock：https://github.com/ideless/yas-lock/releases/tag/v1.0.3-beta1
2. 或抓包+yas-lock加解锁
