### ISSUE TITLE
开一条新的好了，关于圣遗物是否加锁识别错误问题

### ISSUE THREAD

**Issue by Kumacytus** [ideless/artifact#8]
使用yas-lock扫描时
在1600x900及1920x1080分辨率下均出现是否加锁识别错误
表现为部分未加锁的识别为加锁，部分加锁的识别为不加锁
（又因为加解锁是记录位置而不判断圣遗物导致后续再进行加解锁完全错乱…
（期间背包里圣遗物无改动

另外，在全部未加锁下进行识别的话
会有一半圣遗物被识别为加锁

_Originally posted by @Kumacytus in https://github.com/ideless/artifact/issues/4#issuecomment-1144450979_

**Comment by ideless** [comment]
调了一下，在我自己电脑测试没有问题，请更新yas-lock再试试~

**Comment by Kumacytus** [comment]
感谢大佬更新！
但是...这回是圣遗物识别bug了...
识别出了很多重复的圣遗物，还有不存在的佩戴角色。。
分辨率为1600x900
![QQ截图20220611152516](https://user-images.githubusercontent.com/28743469/173178241-cee2f765-bca3-4c84-a4c4-399885d282f7.png)

**Comment by ideless** [comment]
试试这个
https://github.com/ideless/yas-lock/releases/tag/v1.0.3-beta1

**Comment by Kumacytus** [comment]
好了！感谢大佬！
研究一下wireshark去XD
