### ISSUE TITLE
使用抓包工具后，导入解析失败

### ISSUE THREAD

**Issue by koko4396** [ideless/artifact#9]
全部按照流程操作，Windows10系统，使用wireshark抓包，获得pcap文件，将其导入到[圣遗物强化助手]，最后总是解析失败，目前电脑不支持1600*900分辨率，所以无法使用其他工具。是因为我在欧服的关系么?或者是我的pacp文件过大的原因，大概有2Mb，但是目前电脑比较慢，按照流程操作文件就有这么大了。
感谢大佬的工具！！也希望大佬能够解答！！救救孩纸吧，在这里先谢谢大佬了！！

**Comment by ideless** [comment]
f12打开开发者工具看一下报错

**Comment by koko4396** [comment]
> f12打开开发者工具看一下报错
> 
> 我更新了下教程，添加了一个视频教程，你可以看看有没有操作错误

我重新按照视频操作了一遍，还是不行。
报错是这个
fail to set initial key: unknown key 0x4A8D
大概是这个？？
需不需要我把pcap文件也发一下？？？

**Comment by koko4396** [comment]
我怕我操作失误，又试了3次，都是同样的结果

**Comment by ideless** [comment]
是欧服的问题，麻烦再试一次。还用原来的pcap文件就行

**Comment by koko4396** [comment]
> 是欧服的问题，麻烦再试一次。还用原来的pcap文件就行

可以了！！！感谢大佬，大佬牛逼！！！

**Comment by ideless** [comment]
：）
